model:
    max_len: 512
    mname: "t5-small"

train:
    n_epochs: 10
    batch_size: 32
    lr: 0.0005
    early_stop: 1
    patience: 3
    clip: 1
    iters_to_accumulate: 4

peft:
    num_virtual_tokens: 20
    encoder_hidden_size: 128